### ISSUE TITLE
Replace `cat()`

### ISSUE THREAD

**Issue by allenzhuaz** [Merck/gMCPLite#6]

**Comment by allenzhuaz** [comment]
I see some enhancement within `setMethod()` function, seemingly no need to add `verbose` option. But if we use `message()` to replace `cat()`, the displayed font is naturally red. 
This has been discussed in https://github.com/rstudio/rstudio/issues/2574#issuecomment-1064481076
I also do not want to use `rlang::inform()` for now, since it added another dependency.  Not very sure if sticking on `cat()` just for `setMethod()` function is okay, or use `message()` and accept the red font? @nanxstats what do you think?

**Comment by nanxstats** [comment]
Good question. So, it turns out the `show` method in S4 actually controls printing: https://adv-r.hadley.nz/s4.html#show-method . However, I'm ok with replacing these with `message()` to be compliant with the feedback. As an example, renv uses `message()` a lot...

The other places seem to have used `if (verbose) cat(...)` patterns already so we should be good. Also, I think the usage of `cat()` in the vignette is ok - unless we got additional feedback.

We can consider the cli package to get more stylized console messages if necessary in the future.

Overall, I think we are good so am closing this.
